# Generated by Django 4.2.3 on 2023-07-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50, null=True)),
                ('product_img', models.ImageField(null=True, upload_to=None)),
                ('product_des', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
