# Generated by Django 4.2.3 on 2023-08-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterequipment', '0003_products_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(max_length=10000, null=True),
        ),
    ]
