# Generated by Django 4.2.3 on 2023-08-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterequipment', '0006_alter_user_user_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='items_json',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
